version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: mentor_mentee         # Name of the database to create
      POSTGRES_USER: postgres          # Username for the database
      POSTGRES_PASSWORD: postgres  # Password for the user
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
